In [1]:
import numpy as np

In [15]:
myarr=np.array([[1,4,-111,6]],np.int8)

In [10]:
myarr


array([   1,    4, -111,    6], dtype=int8)

In [13]:
myarr[0]

np.int8(1)

In [20]:
myarr[0,1]

np.int8(10)

In [17]:
myarr.shape

(1, 4)

In [18]:
myarr.dtype

dtype('int8')

In [19]:
myarr[0,1]=10

# conversion from other python structures

In [28]:
listarray=np.array([[1,2,3],[2,2,4]])

In [23]:
lisst

array([[1, 2, 3],
       [3, 2, 4]])

In [24]:
listarray.dtype

dtype('int64')

In [26]:
listarray.shape

(2, 3)

In [29]:
listarray.size


6

dictionary


In [30]:
np.array({34,243})

array({34, 243}, dtype=object)

# intrinsic numpy creation objects
 *these are some funtions provided by numpy to create array

In [33]:
z=np.zeros([2])

In [34]:
z

array([0., 0.])

In [35]:
rng=np.arange(14)

In [36]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [42]:
lspace

array([1., 2., 3., 4., 5.])

In [41]:
lspace=np.linspace(1,5,5)

In [6]:
lspace=np.linspace(1,15,5)

In [7]:
lspace


array([ 1. ,  4.5,  8. , 11.5, 15. ])

In [12]:
emp=np.empty((3,2))

In [13]:
emp

array([[1.88626277e-315, 0.00000000e+000],
       [1.88763772e-315, 1.87917995e-315],
       [0.00000000e+000, 5.56507835e-308]])

In [15]:
emp_like=np.empty_like(lspace)

In [16]:
emp_like

array([ 1. ,  4.5,  8. , 11.5, 15. ])

In [18]:
ide=np.identity(24)

In [19]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 

In [20]:
ide.shape

(24, 24)

In [26]:
arr=np.arange(90)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
arr=arr.reshape(3,30)

In [31]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [33]:
arr=arr.ravel()

In [34]:
arr.shape

(90,)

In [38]:
x =np.array([[1,2,3],[4,5,6],[7,8,9]])

In [39]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
s=x.sum(axis=1)

In [47]:
s

array([ 6, 15, 24])

In [48]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
x.flat

In [51]:
for i in x.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [52]:
x.ndim

2

In [54]:
x.size

9

In [56]:
x.nbytes

72

In [65]:
one=np.array([12,33,14,5,16])

In [58]:
one

array([1, 2, 3, 4, 5, 6])

In [61]:
one.argmax()

np.int64(5)

In [63]:
one.min()

np.int64(1)

In [66]:
one.argsort()

array([3, 0, 2, 4, 1])

In [85]:
ara=np.array([[1,2,3,4],[3,2,1,2],[2,1,5,6]])

In [90]:
ara.argmax(axis=0)

array([1, 0, 2, 2])

In [91]:
print(ara)

[[1 2 3 4]
 [3 2 1 2]
 [2 1 5 6]]


In [93]:
ara.argmax(axis=1)

array([3, 0, 3])

In [94]:
ara.ravel()

array([1, 2, 3, 4, 3, 2, 1, 2, 2, 1, 5, 6])

In [96]:
ara.reshape(4,3)

array([[1, 2, 3],
       [4, 3, 2],
       [1, 2, 2],
       [1, 5, 6]])

In [97]:
ara


array([[1, 2, 3, 4],
       [3, 2, 1, 2],
       [2, 1, 5, 6]])

In [98]:
ara2=np.array([[5, 2, 3, 1],
       [7, 2, 1, 5],
       [3, 0, 5, 8]])

In [99]:
ara+ara2

array([[ 6,  4,  6,  5],
       [10,  4,  2,  7],
       [ 5,  1, 10, 14]])

In [101]:
[24,24]+[44,55]

[24, 24, 44, 55]

In [102]:
 ara*ara2


array([[ 5,  4,  9,  4],
       [21,  4,  1, 10],
       [ 6,  0, 25, 48]])

In [103]:
ara

array([[1, 2, 3, 4],
       [3, 2, 1, 2],
       [2, 1, 5, 6]])

In [104]:
ara2

array([[5, 2, 3, 1],
       [7, 2, 1, 5],
       [3, 0, 5, 8]])

In [105]:
  ara@ara2.T

array([[22, 34, 50],
       [24, 36, 30],
       [33, 51, 79]])

In [107]:
ara


array([[1, 2, 3, 4],
       [3, 2, 1, 2],
       [2, 1, 5, 6]])

In [109]:
np.where(ara>2)

(array([0, 0, 1, 2, 2]), array([2, 3, 0, 2, 3]))

In [114]:
np.count_nonzero(ara)

np.int64(11)

In [112]:
ara[0,0]=0

In [115]:
import sys

In [116]:
py_ar=[0,4,55,3]
np_ar=np.array(py_ar)

In [117]:
sys.getsizeof(1)*len(py_ar)

112

In [118]:
np_ar.itemsize *np_ar.size

32

In [119]:
ar.size

12

In [123]:
np_ar.itemsize

8

In [124]:
np_ara.tolist()

[0, 4, 55, 3]

In [127]:
ara

array([[0, 2, 3, 4],
       [3, 2, 1, 2],
       [2, 1, 5, 6]])

In [128]:
ara.tolist()

[[0, 2, 3, 4], [3, 2, 1, 2], [2, 1, 5, 6]]

In [2]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [3]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
mask=arr>=4
print(mask)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [5]:
print(arr[mask])

[4 5 6 7 8 9]


In [6]:
import pandas as pd

# Creating an empty DataFrame
df = pd.DataFrame()

In [7]:
print(df)

Empty DataFrame
Columns: []
Index: []


In [9]:
df=pd.DataFrame([['Sariya','Shuaib'],[92,87]],columns=['Names','Marks'])
df
df['City']=['Kanpur','Lucknow']
df

Names   Marks     City
0  Sariya  Shuaib   Kanpur
1      92      87  Lucknow