In [41]:
import numpy as np    # it is an unofficial standard to use np for numpy
import time

In [42]:
a = np.zeros((4,)); 
a

array([0., 0., 0., 0.])

In [43]:
print(f"np.zeros(4): a={a} , a shape={a.shape} ,a dataype:{a.dtype}")

np.zeros(4): a=[0. 0. 0. 0.] , a shape=(4,) ,a dataype:float64


In [44]:
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64


In [45]:
(4)

4

In [46]:
np.random.random_sample((4,2,2))


array([[[0.44236513, 0.04997798],
        [0.77390955, 0.93782363]],

       [[0.5792328 , 0.53516563],
        [0.80204309, 0.24814448]],

       [[0.59096694, 0.32950282],
        [0.98797985, 0.86846315]],

       [[0.16452144, 0.80277814],
        [0.02503441, 0.89766393]]])

In [47]:
np.arange(5.)

array([0., 1., 2., 3., 4.])

In [48]:
np.random.rand(5)

array([0.41783454, 0.53671084, 0.19721356, 0.26810967, 0.5669563 ])

In [49]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [50]:
a[5].shape

()

In [51]:
a[-2]

np.int64(8)

In [52]:
try:
    c=a[10]
except Exception as e:
    print("The error message you will see is:")
    print(e)

The error message you will see is:
index 10 is out of bounds for axis 0 with size 10


In [53]:
#vector slicing operations
a = np.arange(10)
print(f"a         = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# access 3 elements separated by two 
c = a[2:7:2];     print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];        print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c)

# access all elements
c = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


In [54]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
# negate elements of a
b = -a 
print(f"b = -a        : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]


In [55]:
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")

b = np.sum(a) : 10


In [56]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


In [57]:
c=np.array([1,2])
try:
    d=a+c
except Exception as e:
    print(f"The error is:: {e}")

The error is:: operands could not be broadcast together with shapes (4,) (2,) 


In [58]:
a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = 5 * a 
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


In [60]:
def my_dot(a, b): 
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [61]:
##Speed check 
np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 8.8980 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 1354.4188 ms 


In [65]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5,2], [4,2], [3,2]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 2), np.array: a = [[5 2]
 [4 2]
 [3 2]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


In [72]:
a=np.arange(15).reshape(5,-1)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [74]:
a=np.arange(20).reshape(-1,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [79]:
a[1,2:12:1]

array([12, 13, 14, 15, 16, 17, 18, 19])

In [84]:
a[:,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [88]:
a[1,:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [89]:
a[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])